name: Docker-Selenium

on: [push]

# Define the jobs for different OS's
jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java version
        run: java -version
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=172.17.0.1 -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java version
        run: java -version
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=172.17.0.1 -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}

  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java version
        run: java -version
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=172.17.0.1 -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}
