name: Selenium Grid Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chrome, firefox, edge]
    env:
      SELENIUM_HUB_HOST: localhost
      SELENIUM_HUB_PORT: 4444
      RUN_SCRIPT: |
        mvn clean test -P${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y maven
            sudo apt-get install -y openjdk-17-jdk
            if [ "${{ matrix.browser }}" = "chrome" ]; then
              sudo apt-get install -y chromium-browser
            elif [ "${{ matrix.browser }}" = "firefox" ]; then
              sudo apt-get install -y firefox
            elif [ "${{ matrix.browser }}" = "edge" ]; then
              sudo apt-get install -y microsoft-edge-beta
            fi
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            brew update
            brew install maven
            brew install openjdk@17
            if [ "${{ matrix.browser }}" = "chrome" ]; then
              brew install google-chrome
            elif [ "${{ matrix.browser }}" = "firefox" ]; then
              brew install firefox
            elif [ "${{ matrix.browser }}" = "edge" ]; then
              brew install --cask microsoft-edge-beta
            fi
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            choco install -y maven
            choco install -y jdk17
            if [ "${{ matrix.browser }}" = "chrome" ]; then
              choco install -y googlechrome
            elif [ "${{ matrix.browser }}" = "firefox" ]; then
              choco install -y firefox
            elif [ "${{ matrix.browser }}" = "edge" ]; then
              choco install -y microsoft-edge-beta
            fi
          fi
      - name: Run tests on ${{ matrix.browser }}
        run: ${{ env.RUN_SCRIPT }}
