name: Selenium Tests

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        browser: [chrome, firefox, edge]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker info &>/dev/null; do sleep 1; done

      - name: Setup Docker Compose CLI
        uses: docker/compose-action@${{ env.DOCKER_COMPOSE_VERSION }}
        with:
          compose-version: '2.0.1'

      - name: Start Selenium Grid
        run: |
          docker-compose up -d

      - name: Wait for Selenium Grid to start
        run: |
          for i in {1..30}; do
            curl --fail http://localhost:4444/wd/hub/status && break
            sleep 1
          done

      - name: Run Tests
        run: |
          mvn clean test -P${{ matrix.browser }}

      - name: Stop Selenium Grid
        run: |
          docker-compose down
