name: Docker-Selenium

on: [push]

# Define the jobs for different OS's
jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Check Java version
        run: java -version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=172.17.0.1 -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Check Java version
        run: java -version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=172.17.0.1 -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}

  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Check Java version
        run: java -version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Docker
        uses: actions/setup-docker-macos-action@master
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=172.17.0.1 -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}
