name: Docker-Selenium

on: [push]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}-latest
    env:
      SELENIUM_HUB_HOST: 172.17.0.1
      SELENIUM_HUB_PORT: 4444
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and test
        run: |
          docker run -e SELENIUM_HUB_HOST=${SELENIUM_HUB_HOST} -d -p 4444:4444 selenium/standalone-${{ matrix.browser }}:latest
          mvn clean test -P${{ matrix.browser }}
