name: Selenium Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        profile: [chrome, firefox, edge]
    env:
      SELENIUM_HUB_HOST: $HOSTNAME
      SELENIUM_HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install Docker (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: Start Selenium Grid
        run: docker run -d -p $SELENIUM_HUB_PORT:$SELENIUM_HUB_PORT --shm-size=2g selenium/hub:latest
        id: selenium-hub
      - name: Start Selenium Node (Chrome)
        run: docker run -d --shm-size=2g -e HUB_HOST=$HOSTNAME selenium/node-chrome:latest
        if: matrix.profile == 'chrome'
        id: selenium-node-chrome
      - name: Start Selenium Node (Firefox)
        run: docker run -d --shm-size=2g -e HUB_HOST=$HOSTNAME selenium/node-firefox:latest
        if: matrix.profile == 'firefox'
        id: selenium-node-firefox
      - name: Start Selenium Node (Edge)
        run: docker run -d --shm-size=2g -e HUB_HOST=$HOSTNAME selenium/node-edge:latest
        if: matrix.profile == 'edge'
        id: selenium-node-edge
      - name: Build and test with Maven
        run: mvn clean test -P${{ matrix.profile }}
