name: Selenium Tests

on: [push]
      
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker (macOS)
        uses: docker-practice/actions-setup-docker@master    

      - name: Install Docker Compose on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Install Docker Compose on macOS
        if: matrix.os == 'macOS-latest'
        run: |
          brew install docker-compose
          
      - name: Install Docker Compose on Windows
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest "https://github.com/docker/compose/releases/download/$env:DOCKER_COMPOSE_VERSION/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile docker-compose.exe
          Move-Item -Path .\docker-compose.exe -Destination C:\Windows\system32\docker-compose.exe
          
      - name: Start Selenium Grid
        run: |
          docker-compose up -d

      - name: Wait for Selenium Grid to start
        run: |
          for i in {1..30}; do
            curl --fail http://localhost:4444/wd/hub/status && break
            sleep 1
          done

      - name: Run Tests
        run: |
          mvn clean test -P${{ matrix.browser }}

      - name: Stop Selenium Grid
        run: |
          docker-compose down
